export const COLOR_MAPPER: any = {
    "Codes": 'danger'
};

export const THEMES: any = [
    "a11yDark",
    "a11yLight",
    "anOldHope",
    "androidstudio",
    "arta",
    "atomOneDark",
    "atomOneLight",
    "codepen",
    "dracula",
    "far",
    "github",
    "googlecode",
    "hopscotch",
    "hybrid",
    "irBlack",
    "monoBlue",
    "monokaiSublime",
    "monokai",
    "nord",
    "noctisViola",
    "obsidian",
    "ocean",
    "paraisoDark",
    "paraisoLight",
    "pojoaque",
    "purebasic",
    "railscast",
    "rainbow",
    "shadesOfPurple",
    "solarizedDark",
    "solarizedLight",
    "sunburst",
    "tomorrowNightBlue",
    "tomorrowNightBright",
    "tomorrowNightEighties",
    "tomorrowNight",
    "tomorrow",
    "vs2015",
    "xt256",
    "zenburn"
];